### ISSUE TITLE
Transitioning from Reactify -> Babelify

### ISSUE THREAD

**Issue by kevindieu100** [jogleasonjr/react-bootstrap-starter#4]
Hi, I'm having a hard time trying to figure out how to transition from Reactify to Babelify in the gulp files. Do you think you can help me with this? Thank you so much!

**Comment by jogleasonjr** [comment]
Hi @kevindieu100 

This project doesn't use Babelify, and I'm sorry to say I haven't used Babel with the explicit transforms using gulp. From my knowledge of the moving pieces, it seems like [this answer](http://stackoverflow.com/a/33187826) might be close to what you're looking for.

After this project I switched to [Webpack](http://webpack.github.io/docs/tutorials/getting-started/) for my bundling and transforming needs. You can see where I implemented Babel with the React transform preset [here](https://github.com/jogleasonjr/react-webpack-scss-quickstart/blob/master/webpack.config.js#L72).
